repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: pdm run lint_black
        language: system
        types: [python]
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: pdm run lint_mypy
        language: system
        types: [python]
        pass_filenames: false
      - id: pytest
        name: pytest
        entry: pdm run tests
        language: system
        types: [python]
        pass_filenames: false
      - id: ruff
        name: ruff
        entry: pdm run lint_ruff
        language: system
        types: [python]
        pass_filenames: false
