repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: docker
        language: system
        types: [python]
        args: [
          "compose",
          "run",
          "--interactive=false",
          "--volume=datajoint-link:/src",
          "black",
        ]
      - id: isort
        name: isort
        entry: docker
        language: system
        types: [python]
        args: [
          "compose",
          "run",
          "--interactive=false",
          "--volume=datajoint-link:/src",
          "isort",
        ]
      - id: mypy
        name: mypy
        entry: docker
        language: system
        types: [python]
        args: [
          "compose",
          "run",
          "--interactive=false",
          "--volume=datajoint-link:/src",
          "mypy",
        ]
        pass_filenames: false
      - id: flake8
        name: flake8
        entry: docker
        language: system
        types: [python]
        args: [
          "compose",
          "run",
          "--interactive=false",
          "--volume=datajoint-link:/src",
          "flake8",
        ]
      - id: pylint
        name: pylint
        entry: docker
        language: system
        types: [python]
        args: [
          "compose",
          "run",
          "--interactive=false",
          "--volume=datajoint-link:/src",
          "pylint",
        ]
