repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: docker compose run --interactive=false black
        language: system
        types: [python]
      - id: isort
        name: isort
        entry: docker compose run --interactive=false isort
        language: system
        types: [python]
      - id: mypy
        name: mypy
        entry: docker compose run --interactive=false mypy
        language: system
        types: [python]
        pass_filenames: false
      - id: flake8
        name: flake8
        entry: docker compose run --interactive=false flake8
        language: system
        types: [python]
      - id: pylint
        name: pylint
        entry: docker compose run --interactive=false pylint
        language: system
        types: [python]
      - id: pytest
        name: pytest
        entry: docker compose run --interactive=false pytest -m='not slow'
        language: system
        types: [python]
        pass_filenames: false
