version: "3.8"
name: datajoint-link
services:
  dev:
    build:
      context: .
      args:
        BASE: cblessing24/python3.8:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - datajoint-link:/src
    command: "tmux"
  pytest:
    image: cblessing24/datajoint-link:latest
    volumes:
      - datajoint-link:/src
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_NETWORK: datajoint-link_test
    networks:
      - test
    command: ["pytest"]
  pytest_github:
    image: cblessing24/datajoint-link:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./reports:/src/reports
    environment:
      DOCKER_NETWORK: datajoint-link_test
    networks:
      - test
    command: [
      "pytest", 
      "--cov", 
      "--cov-report=xml:/src/reports/coverage.xml",
      "--cov-config=pyproject.toml", # Workaround for https://github.com/nedbat/coveragepy/issues/512
    ]
  black:
    image: cblessing24/datajoint-link:latest
    command: ["black", "--check", "--diff", "."]
  isort:
    image: cblessing24/datajoint-link:latest
    command: ["isort", "--check-only", "--diff", "."]
  mypy:
    image: cblessing24/datajoint-link:latest
    command: ["mypy"]
  flake8:
    image: cblessing24/datajoint-link:latest
    command: ["flake8", "."]
  pylint:
    image: cblessing24/datajoint-link:latest
    command: ["pylint", "dj_link"]
  profile:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/src/datajoint-link
      - pypackages:/src/datajoint-link/__pypackages__
    networks:
      - profiling_network
    entrypoint: ["./entrypoints/profile_entrypoint.sh"]

networks:
  profiling_network:
    name: profiling_network
  test:

volumes:
  pypackages:
  datajoint-link:
