version: "3.8"
services:
  dev:
    build:
      context: .
      args:
        BASE: cblessing24/python3.8:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - datajoint-link:/src
    command: "tmux"
  pytest:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/src/datajoint-link
      - pypackages:/src/datajoint-link/__pypackages__
    networks:
      - test_runner_network
    entrypoint: ["./entrypoints/pytest_entrypoint.sh"]
  profile:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/src/datajoint-link
      - pypackages:/src/datajoint-link/__pypackages__
    networks:
      - profiling_network
    entrypoint: ["./entrypoints/profile_entrypoint.sh"]

networks:
  profiling_network:
    name: profiling_network
  test_runner_network:
    name: test_runner_network

volumes:
  pypackages:
  datajoint-link:
