version: "3.8"
name: datajoint-link
services:
  build:
    build: .
    volumes:
      - $PWD/dist:/src/dist
    entrypoint: ["pdm", "build"]
  functional_tests:
    build: .
    volumes:
      - $PWD/link:/src/link:ro
      - $PWD/tests:/src/tests:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_NETWORK: datajoint-link_test
    networks:
      - test
    entrypoint: ["pdm", "run", "pytest"]
    command: ["tests/functional"]
  tests_with_coverage:
    build: .
    volumes:
      - $PWD/link:/src/link:ro
      - $PWD/tests:/src/tests:ro
      - $PWD/reports:/src/reports
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_NETWORK: datajoint-link_test
    networks:
      - test
    command: [
      "pytest", 
      "--cov", 
      "--cov-report=xml:/src/reports/coverage.xml",
      "--cov-config=pyproject.toml", # Workaround for https://github.com/nedbat/coveragepy/issues/512
    ]
  black:
    build: .
    command: ["lint_black"]
  mypy:
    build: .
    command: ["lint_mypy"]
  ruff:
    build: .
    command: ["lint_ruff"]

networks:
  test:
