name: ci

on: [push, pull_request]

jobs:
  build_image:
    runs-on: ubuntu-20.04
    outputs:
      imageid: ${{ steps.build.outputs.imageid }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and export
        id: build
        uses: docker/build-push-action@v4
        with:
          tags: cblessing24/datajoint-link:latest
          outputs: type=docker,dest=/tmp/image.tar
      - name: Upload image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: image
          path: /tmp/image.tar
  lint:
    needs: build_image
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        linter: ["black", "isort", "mypy", "flake8", "pylint"]
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: image
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/image.tar
      - name: Check out code
        uses: actions/checkout@v3
      - name: Lint code
        run: touch .env && docker compose run ${{ matrix.linter }}
  test:
    needs: build_image
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: image
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/image.tar
      - name: Check out code
        uses: actions/checkout@v3
      - name: Test code
        run: touch .env && docker compose run pytest_github
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
  push_image:
    needs: [build_image, lint, test]
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: image
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/image.tar
      - name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image
        run: |
          docker tag cblessing24/datajoint-link:latest cblessing24/datajoint-link:${{ github.sha }}
          docker push cblessing24/datajoint-link:latest
          docker push cblessing24/datajoint-link:${{ github.sha }}
  publish_package:
    if: startsWith(github.ref, 'refs/tags/v') && github.repository_owner == 'sinzlab'
    needs: [build_image, lint, test]
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: image
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/image.tar
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build distribution artifacts
        run: touch .env && docker compose run build
      - name: Upload distribution packages to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
